"""Fetch current Magic Kingdom wait times and store one timestamped snapshot.

This is the canonical ingestion logic. It runs on a timer inside Azure Functions
(see function_app.py) and can also be run directly for a manual snapshot:

    python functions/ingest_core.py

Configuration comes from environment variables in both cases — Application
Settings on Azure, a local .env when run by hand.
"""

import logging
import os
from datetime import datetime, timezone

import httpx
import psycopg2

log = logging.getLogger(__name__)

# Park 6 is Magic Kingdom.
QUEUE_TIMES_URL = "https://queue-times.com/parks/6/queue_times.json"
PARK_NAME = "Magic Kingdom"

CREATE_TABLE = """
    CREATE TABLE IF NOT EXISTS wait_times (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        ride_name VARCHAR(255) NOT NULL,
        park_name VARCHAR(255) NOT NULL,
        wait_minutes INTEGER NOT NULL,
        is_open BOOLEAN NOT NULL,
        recorded_at TIMESTAMP NOT NULL
    )
"""

INSERT_ROW = """
    INSERT INTO wait_times
        (ride_name, park_name, wait_minutes, is_open, recorded_at)
    VALUES (%s, %s, %s, %s, %s)
"""


def get_conn():
    return psycopg2.connect(
        host=os.environ.get("DB_HOST", "localhost"),
        port=os.environ.get("DB_PORT", "5432"),
        dbname=os.environ.get("DB_NAME", "disneywaits"),
        user=os.environ.get("DB_USER", "disney"),
        password=os.environ.get("DB_PASSWORD", "magic"),
        sslmode=os.environ.get("DB_SSLMODE", "prefer"),
        connect_timeout=20,
    )


def fetch_wait_times():
    response = httpx.get(QUEUE_TIMES_URL, timeout=20)
    response.raise_for_status()
    return response.json()


def ingest() -> int:
    """Capture one snapshot. Returns the number of rows inserted."""
    data = fetch_wait_times()

    # Always UTC, never the host's local clock. recorded_at is a naive TIMESTAMP
    # column, so a run from a machine on Eastern would silently mix mislabeled rows
    # into a UTC dataset. Readers convert to park time at query time.
    recorded_at = datetime.now(timezone.utc)
    inserted = 0

    with get_conn() as conn:
        with conn.cursor() as cursor:
            cursor.execute(CREATE_TABLE)
            for land in data["lands"]:
                for ride in land["rides"]:
                    cursor.execute(
                        INSERT_ROW,
                        (
                            ride["name"],
                            PARK_NAME,
                            ride["wait_time"],
                            ride["is_open"],
                            recorded_at,
                        ),
                    )
                    inserted += 1
        conn.commit()

    log.info("Inserted %d records at %s", inserted, recorded_at)
    return inserted


if __name__ == "__main__":
    logging.basicConfig(
        level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s"
    )
    # Only for hand-runs; on Azure the settings are already in the environment.
    try:
        from dotenv import load_dotenv

        load_dotenv(
            os.path.join(os.path.dirname(__file__), "..", "pipeline", ".env")
        )
    except ImportError:
        pass

    print(f"inserted {ingest()} rows")
