import logging
import os
from datetime import datetime

import httpx
import psycopg2
from dotenv import load_dotenv

logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")
log = logging.getLogger(__name__)

load_dotenv()


def get_conn():
    return psycopg2.connect(
        host=os.environ.get("DB_HOST", "localhost"),
        port=os.environ.get("DB_PORT", "5432"),
        dbname=os.environ.get("DB_NAME", "disneywaits"),
        user=os.environ.get("DB_USER", "disney"),
        password=os.environ.get("DB_PASSWORD", "magic"),
        sslmode=os.environ.get("DB_SSLMODE", "prefer"),
    )


def fetch_wait_times():
    response = httpx.get(
        "https://queue-times.com/parks/6/queue_times.json", timeout=10
    )
    response.raise_for_status()
    return response.json()


def ingest():
    data = fetch_wait_times()
    recorded_at = datetime.now()
    inserted = 0

    with get_conn() as conn:
        with conn.cursor() as cursor:
            cursor.execute("""
                CREATE TABLE IF NOT EXISTS wait_times (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    ride_name VARCHAR(255) NOT NULL,
                    park_name VARCHAR(255) NOT NULL,
                    wait_minutes INTEGER NOT NULL,
                    is_open BOOLEAN NOT NULL,
                    recorded_at TIMESTAMP NOT NULL
                )
            """)
            for land in data["lands"]:
                for ride in land["rides"]:
                    cursor.execute(
                        """
                        INSERT INTO wait_times
                            (ride_name, park_name, wait_minutes, is_open, recorded_at)
                        VALUES (%s, %s, %s, %s, %s)
                        """,
                        (ride["name"], "Magic Kingdom", ride["wait_time"], ride["is_open"], recorded_at),
                    )
                    inserted += 1
        conn.commit()

    log.info("Inserted %d records at %s", inserted, recorded_at)


if __name__ == "__main__":
    ingest()
