import os
import httpx
import psycopg2
from datetime import datetime
from dotenv import load_dotenv

# Load DB settings from a .env file if present (see .env.example)
load_dotenv()

# Database connection — defaults target local Postgres; override via .env for Azure
conn = psycopg2.connect(
    host=os.environ.get("DB_HOST", "localhost"),
    port=os.environ.get("DB_PORT", "5432"),
    dbname=os.environ.get("DB_NAME", "disneywaits"),
    user=os.environ.get("DB_USER", "disney"),
    password=os.environ.get("DB_PASSWORD", "magic"),
    sslmode=os.environ.get("DB_SSLMODE", "prefer"),
)
cursor = conn.cursor()

# Ensure the table exists (mirrors the WaitTime JPA model so the pipeline can
# run against a fresh database without the backend having booted first)
cursor.execute("""
    CREATE TABLE IF NOT EXISTS wait_times (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        ride_name VARCHAR(255) NOT NULL,
        park_name VARCHAR(255) NOT NULL,
        wait_minutes INTEGER NOT NULL,
        is_open BOOLEAN NOT NULL,
        recorded_at TIMESTAMP NOT NULL
    )
""")

# Fetch Magic Kingdom wait times from Queue-Times API
# Park ID 6 = Magic Kingdom
response = httpx.get("https://queue-times.com/parks/6/queue_times.json")
data = response.json()

recorded_at = datetime.now()
inserted = 0

# Loop through each ride and insert into database
for land in data["lands"]:
    for ride in land["rides"]:
        cursor.execute("""
                       INSERT INTO wait_times (ride_name, park_name, wait_minutes, is_open, recorded_at)
                       VALUES (%s, %s, %s, %s, %s)
                       """,
                       (
                           ride["name"],
                           "Magic Kingdom",
                           ride["wait_time"],
                           ride["is_open"],
                           recorded_at
                       ))
        inserted += 1
conn.commit()
cursor.close()
conn.close()

print(f"Successfully inserted {inserted} wait time records at {recorded_at}")