spring.application.name=backend

spring.datasource.url=jdbc:postgresql://localhost:5432/disneywaits
spring.datasource.username=disney
spring.datasource.password=magic
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true